[build]
  base = "flutter_app"
  publish = "build/web"
  command = """
    git clone https://github.com/flutter/flutter.git --depth 1 --branch stable $HOME/flutter &&
    export PATH="$PATH:$HOME/flutter/bin" &&
    flutter doctor &&
    flutter build web --release
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200